# Generated by Django 3.2.7 on 2022-01-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learned_material',
            field=models.ManyToManyField(null=True, to='learning.Material'),
        ),
    ]
