# Generated by Django 3.2.7 on 2022-01-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_student_learned_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='learned_material',
            field=models.ManyToManyField(blank=True, to='learning.Material'),
        ),
    ]
